'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace PageControlWithinCallbackPanel.TabsContent


    Partial Public Class TabContentType1

        ''' <summary>
        ''' HtmlEditor control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HtmlEditor As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditor

        ''' <summary>
        ''' SampleButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SampleButton As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
