'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace PageControlWithinCallbackPanel.TabsContent


    Partial Public Class TabContentType2

        ''' <summary>
        ''' grid control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected grid As Global.DevExpress.Web.ASPxGridView

        ''' <summary>
        ''' AccessDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource
    End Class
End Namespace
